ActsAsVotable::Vote.create!([
  {votable_type: "Talk", votable_id: 1, voter_type: "User", voter_id: 1, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 2, voter_type: "User", voter_id: 1, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 3, voter_type: "User", voter_id: 1, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 4, voter_type: "User", voter_id: 1, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 5, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 1, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 3, voter_type: "User", voter_id: 2, vote_flag: false, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 2, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 4, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 6, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 7, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 8, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1},
  {votable_type: "Talk", votable_id: 9, voter_type: "User", voter_id: 2, vote_flag: true, vote_scope: nil, vote_weight: 1}
])
User.create!([
  {email: "anna.green@test.com", encrypted_password: "$2a$12$HY88lSXAeuSx49ispy2g1uiuCV38yGUwoynWe5YA3JGu.9ZCl0f1S", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, first_name: "Anna", last_name: "Green", nickname: "anna_gr", photo: nil, dob: "2001-10-10", admin: false},
  {email: "tom.cruse@test.com", encrypted_password: "$2a$12$qB7YQW7uzpV9imbdP8qhOuNh9cCLmyhljhK30sZNkP3Gt98HGAX0W", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, first_name: "Tom", last_name: "Cruse", nickname: "tom$$$", photo: nil, dob: "1980-01-01", admin: false}
])
Comment.create!([
  {body: "Hi! I totally disagree.", user_id: 2, talk_id: 3, parent_id: nil},
  {body: "Hi! It`s amazing!!!", user_id: 2, talk_id: 2, parent_id: nil},
  {body: "Hi! I am dreaming about that wonderful place.", user_id: 2, talk_id: 1, parent_id: nil},
  {body: "Thanks, Anna!", user_id: 1, talk_id: 2, parent_id: nil},
  {body: "Test reply from Tom to Anna.", user_id: 1, talk_id: 2, parent_id: 2},
  {body: "I hope you will be there soon!", user_id: 1, talk_id: 1, parent_id: 3},
  {body: "Anna, do you have a better recipe?", user_id: 1, talk_id: 3, parent_id: 1}
])
Favorite.create!([
  {favoritable_type: "Talk", favoritable_id: 1, favoritor_type: "User", favoritor_id: 2, scope: "favorite", blocked: false},
  {favoritable_type: "Talk", favoritable_id: 4, favoritor_type: "User", favoritor_id: 2, scope: "favorite", blocked: false}
])
Feedback.create!([
  {recommendation: "yes", experience: "This Site is comfortable in use There many interesting stories and a wide variety of themes. Greate thanks.", user_id: 1},
  {recommendation: "yes", experience: "The site is very user-friendly.  There are many interesting talks and a wide variety of themes. I regularly update my story and participate in discussions. Great thanks.", user_id: 2}
])
Talk.create!([
  {title: "Kali, the Lion", text: "Kali knows how it feels to be part of the most feared gang in the Serengeti. Lions are the only cats who live in big groups2 and at the heart of Kali’s pride is a formidable sisterhood of lionesses. These powerfully-built providers who take on the lion’s share (as it were) of hunting for the group, and protect their cubs fiercely. While the lionesses hunt, the males babysit - protecting the pride and the territory from rival males who will oust them and kill the cubs at the first sign of weakness. Even for apex predators, danger lurks in the long grasses. Kali knows these dangers well. She was exiled from the group when she had cubs with an outsider. It took all of her fortitude to keep herself and her babies alive while she worked to regain the pride’s trust. Back in the fold, Kali enjoys the strength in numbers. When trouble comes, she will defend this family with her life - she may have to.", photo: nil, user_id: 1, theme: "Nature", cached_votes_total: 2, cached_votes_score: 2, cached_votes_up: 2, cached_votes_down: 0, cached_weighted_score: 2, cached_weighted_total: 2, cached_weighted_average: 1.0},
  {title: "How to make better mashed potatoes — just the way you like them", text: "Family feuds have erupted over less trivial things than how to make mashed potatoes. Now, you may say mashed potatoes are, in fact, trivial, but I and plenty of other people would beg to differ — especially when it comes to which version gets served at Thanksgiving. (Raise your hand if you, too, have served multiple types to please various tastes.)\r\nSo, no, I am not going to take a side in your ongoing family dispute. What I am going to do is tell you how to tweak ingredients and techniques to achieve your — or your guests’ — ideal result.\r\nWhether you want fluffy or creamy (or gluey, no judgment here), cheesy or garlicky or any other type of spud, here’s what you need to know about the different variables.\r\nType of potato. The potato you use is a primary factor in what your mashed potatoes will be like. Potatoes generally fall into two categories, Harold McGee says in “On Food and Cooking”: mealy and waxy, which correspond to high- and low-starch contents.", photo: nil, user_id: 1, theme: "Lifestyle", cached_votes_total: 2, cached_votes_score: 0, cached_votes_up: 1, cached_votes_down: 1, cached_weighted_score: 0, cached_weighted_total: 2, cached_weighted_average: 0.0},
  {title: "Nalla, the Elephant", text: "Family is everything to Nalla, the wise matriarch of the elephant herd. For this group of majestic giants, a problem for one is a problem for all - a fallen calf is scooped up by many trunks; when a threat appears, the large, fearless females form a barrier to protect their young. Even lions, those fearless hunters, generally accept that confrontation is futile against the world’s largest living land mammals.4 Attacks are rare. But danger comes in many forms and Nalla faces difficult decisions daily - whether navigating the herd’s migration, surviving the Serengeti’s hostile elements or negotiating complex relationships when bulls enter (and leave) the fold. Nalla was made for this - elephants have the largest brains in the animal kingdom, high emotional intelligence and elemental intelligence too - they can even hear clouds approaching.5 She will never let the herd down. But on the Serengeti, storm clouds are never far away, and even the wisest leaders face tests that threaten to overwhelm them.", photo: nil, user_id: 2, theme: "Nature", cached_votes_total: 1, cached_votes_score: 1, cached_votes_up: 1, cached_votes_down: 0, cached_weighted_score: 1, cached_weighted_total: 1, cached_weighted_average: 1.0},
  {title: "A Beach Paradise In The North Of Sumatra: Pulau Weh.", text: "As you know, Indonesia is one of our absolute favourite travel destinations. Since our first visit in 1995, we’ve probably been here more than 20 times. From Sumatra all the way to Irian Jaya (or West Papua as it’s mostly called today) we’ve had our most memorable travel experiences, met wonderful people who later became friends and have seen things that most people will never get the chance to. Indonesia is a true paradise from A to Z. And our most recent destination was the norther most tip of Indonesia: a little island called Pulau Weh.\r\nEspecially during the Christmas holidays, princes surge through the roof in many places across Asia. We’re not willing to spend thousands of Dollars in a place that is then swamped by tourists, so if you’re looking for a tropical paradise, that’s still rather unknown and where you actually get your money’s worth, then this island off the coast of Aceh is the perfect spot.\r\nCasa Nemo is definitely the best place to stay at on the island. Not only because the resort itself is amazing (review coming up), but also because the beach here is the nicest one on the island. And now I’ll let the photos speak for themselves.", photo: nil, user_id: 1, theme: "Traveling", cached_votes_total: 2, cached_votes_score: 2, cached_votes_up: 2, cached_votes_down: 0, cached_weighted_score: 2, cached_weighted_total: 2, cached_weighted_average: 1.0},
  {title: "So, you want to be a backcountry skier", text: "Even before the pandemic, skiers and snowboarders were flocking to the country’s backcountry mountain areas. Their reasons varied. Some hoped to avoid crowds, others to avoid paying for lift tickets. Others were thrill-seekers following in the steps of their favorite action-movie stars. Whatever the reason, they were willing to climb uphill under their own steam in return for the chance to ski downhill on untracked snow.\r\nBut after the coronavirus pandemic hit, interest in the backcountry skyrocketed. Between August 2020 and March 2021, sales of backcountry touring equipment — skis, boots and bindings — were up 115 percent compared with the same period over the previous years, according to market research from Snowsports Industries America, an industry trade group. Accessory sales — avalanche beacons, shovels and probes — were up 87 percent, and sales of splitboards (backcountry-specific snowboards that split in half lengthwise, so users can climb uphill the same as skiers) for that same period increased 92 percent.\r\nThe term “backcountry” refers to terrain that is out of bounds from ski resorts, often accessed by a trailhead, although some people head into the backcountry from a gate at a resort boundary. Unlike ski resorts, which use explosives and other mechanisms to keep inbounds slopes from avalanching during ski days, the backcountry is uncontrolled. There is neither avalanche mitigation nor a ski patrol to arrive within minutes of an accident and whisk injured folks to safety. Once you leave the trailhead, you’re on your own.", photo: nil, user_id: 1, theme: "Lifestyle", cached_votes_total: 2, cached_votes_score: 2, cached_votes_up: 2, cached_votes_down: 0, cached_weighted_score: 2, cached_weighted_total: 2, cached_weighted_average: 1.0},
  {title: "Five simple ways in which you can balance your cheat meals and not feel guilty", text: "1. Fasting\r\nSixteen hours of fasting post your cheat meal is an effective way to break the craving cycle and achieve discipline again.\r\n2. Protein and veggies\r\nThe day after your cheat day, choose a high protein and veggie plan; it will help to keep your insulin from spiking.\r\n3. Low-calorie diet\r\nTry to choose a low-calorie, high-fibre food to balance your cheat meals. Fibre will give your stomach the fullness it needs. You can incorporate psyllium husk in your meal preparation or consume it with water pre-meals.\r\n4. Burn the calorie\r\nGetting back to routine post a cheat-meal day means not missing on your workout. If not working out, then a 60 minutes walk will be helpful.\r\n5. Hydrate\r\nCheat meals consist of high sodium and sugary foods. These toxins need to be flushed out of your system. Drinking 2-2.5 litre of water is a must.", photo: nil, user_id: 2, theme: "Lifestyle", cached_votes_total: 1, cached_votes_score: 1, cached_votes_up: 1, cached_votes_down: 0, cached_weighted_score: 1, cached_weighted_total: 1, cached_weighted_average: 1.0},
  {title: "Shavu and Shaba, the Jackals", text: "Why bother going to all the bother of hunting when you can get someone else to do it for you? That’s Shavu and Shaba’s philosophy - a crafty young pair of jackals who find that dinner is all the more delicious when you haven’t had to bloody your paws catching it yourself. The only problem is getting rid of the pesky hunters who wilfully refuse to hand over their haul. This is where team work comes in - jackals are one of the few mammals who mate for life,6 and Shavu and Shaba are in this together. Their long legs, peerless cooperation and reckless attitude towards personal safety helps them run rings around the lions and hyenas who wind up losing their prizes. But confidence only gets you so far - Shavu and Shaba must be careful that they don’t wind up as someone’s dinner themselves.", photo: nil, user_id: 2, theme: "Nature", cached_votes_total: 1, cached_votes_score: 1, cached_votes_up: 1, cached_votes_down: 0, cached_weighted_score: 1, cached_weighted_total: 1, cached_weighted_average: 1.0},
  {title: "Shani, the Zebra", text: "Life is very different when you’re the hunted rather than the hunter. As leader of the zebras, every day is a dice with death for Shani and her herd. With a fawn in tow, the dangers are doubled. But Shani is resourceful - using everything at her disposal to survive. Zebras have excellent eyesight and hearing,7 an alarm system against predators. They run in zigzags to deter their pursuers, and then there’s their iconic stripes. Scientists don’t know for sure why zebras have stripes, but one leading theory purports that they dazzle the hunter, making it difficult to pick out individual zebras from the galloping herd.8 But not all threats lurk outside the zebra clan - a strong female like Shani is highly prized and her brave stallion Punda must fight relentlessly to prevent rival males from stealing her from the herd and even killing her foal.", photo: nil, user_id: 2, theme: "Nature", cached_votes_total: 1, cached_votes_score: 1, cached_votes_up: 1, cached_votes_down: 0, cached_weighted_score: 1, cached_weighted_total: 1, cached_weighted_average: 1.0},
  {title: "Mzuri and Dada, the Leopard cubs ", text: "Life on the Serengeti is a riot of colour, smells and excitement for this adorable pair of sister cubs. Their big eyes drink in the new exciting world they’ve tumbled into. Leopards live in a variety of habitats across Africa - from mountains to deserts and grasslands like the ones that Mzuri and Dada play in. But as inviting as this new world seems, dangers lurk around every corner and cuteness is no protection. The cubs will grow to be ferocious predators, solitary hunters who ambush their prey - baboons, antelopes and gazelles - when they can catch them.9 But while young they are vulnerable. Childhood is short lived in the Serengeti. Mzuri and Dada must learn the skills to survival quickly in order to see their future.", photo: nil, user_id: 2, theme: "Nature", cached_votes_total: 1, cached_votes_score: 1, cached_votes_up: 1, cached_votes_down: 0, cached_weighted_score: 1, cached_weighted_total: 1, cached_weighted_average: 1.0}
])
ActiveStorage::Attachment.create!([
  {name: "photo", record_type: "Talk", record_id: 1, blob_id: 3},
  {name: "photo", record_type: "Talk", record_id: 2, blob_id: 4},
  {name: "photo", record_type: "Talk", record_id: 4, blob_id: 6},
  {name: "photo", record_type: "Talk", record_id: 3, blob_id: 7},
  {name: "photo", record_type: "User", record_id: 2, blob_id: 8},
  {name: "photo", record_type: "Talk", record_id: 5, blob_id: 9},
  {name: "photo", record_type: "Talk", record_id: 6, blob_id: 10},
  {name: "photo", record_type: "Talk", record_id: 7, blob_id: 11},
  {name: "photo", record_type: "Talk", record_id: 8, blob_id: 12},
  {name: "photo", record_type: "Talk", record_id: 9, blob_id: 13},
  {name: "photo", record_type: "User", record_id: 1, blob_id: 14}
])
ActiveStorage::Blob.create!([
  {key: "aavd8660ymueojh05l6l6d1mo0c1", filename: "FB_IMG_1632073795461.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 251324, checksum: "cIBk1nHltxWme5IJxfNNKg=="},
  {key: "jkrbhqjyh73n8yd40bwbb76ae890", filename: "Kali_lion.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 538482, checksum: "FxiJc4gDl72NBIz1hfJqkg=="},
  {key: "zjyj3uny0vopx9pyx8fm7se77ppu", filename: "imrs-2.jpg", content_type: "image/webp", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 85044, checksum: "zD9kpF0vKR9hHQdy/VqXpg=="},
  {key: "foili3qfpdejcz6f08w9fj611tyk", filename: "imrs-1.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 144650, checksum: "Y03C3e7E//64wfgWpEMi4A=="},
  {key: "g16s3bgzxy586vjgxvzvnrcdaoy2", filename: "user_8.png", content_type: "image/png", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 388768, checksum: "jg4Rj8yKcnDPQZacloguaw=="},
  {key: "9ltfpyomesj8b932rko64cmcm5m0", filename: "Nalla_elephant.jpg", content_type: "image/webp", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 1284388, checksum: "8tMBBqfkTd5cDDq1GuAyAA=="},
  {key: "hj60mm49jiisuhuijd4fofs99no2", filename: "food-balance.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 22130, checksum: "Xbi//k8EHcaMGjPZ+Lh5Hg=="},
  {key: "2seh8m66lg9ikz3w6nwfudln6k5m", filename: "Shavu&Shaba.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 304122, checksum: "97i0D02q9xv0jqUpXIm0ig=="},
  {key: "6dg1wvc5j0kqda0kdnxsdt565cf9", filename: "Shani_zebra.jpg", content_type: "image/webp", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 343100, checksum: "G7mwKAaLMuGh8G3ic8B5ig=="},
  {key: "c5ehvv2edyepouzmnbiuhbwrpj1f", filename: "Mzuri&Dada.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 294115, checksum: "W7tpLJR4Y7x36oXNhJrglQ=="},
  {key: "og2ijtajy0rnoj8y6h7kawb1g49q", filename: "user_12.jpg", content_type: "image/jpeg", metadata: {"identified"=>true, "analyzed"=>true}, service_name: "local", byte_size: 86456, checksum: "QhomhmZ/ORJcY7G9Q/mqRw=="}
])
